/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Attribute descriptor.
 *
 */
class Attribute {
  /**
   * Create a Attribute.
   * @member {string} name A human readable, unique attribute ID, e.g.
   * 'device_type', 'ip_addr', 'cpu_load', etc.
   * @member {string} [description] Attribute description.
   * @member {string} value The current value of the attribute.
   *
   * Attribute type is implicit, inferred from the JSON type.
   *
   * Supported types: number, string, array of numbers, array of strings. Mixed
   * arrays are not allowed.
   */
  constructor() {
  }

  /**
   * Defines the metadata of Attribute
   *
   * @returns {object} metadata of Attribute
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Attribute',
      type: {
        name: 'Composite',
        className: 'Attribute',
        modelProperties: {
          name: {
            required: true,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          description: {
            required: false,
            serializedName: 'description',
            type: {
              name: 'String'
            }
          },
          value: {
            required: true,
            serializedName: 'value',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = Attribute;
