/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a Device.
 */
class Device {
  /**
   * Create a Device.
   * @member {string} [id] Mender-assigned unique ID.
   * @member {string} [updatedTs] Timestamp of the most recent attribute
   * update.
   * @member {array} [attributes] A list of attribute descriptors.
   */
  constructor() {
  }

  /**
   * Defines the metadata of Device
   *
   * @returns {object} metadata of Device
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Device',
      type: {
        name: 'Composite',
        className: 'Device',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          updatedTs: {
            required: false,
            serializedName: 'updated_ts',
            type: {
              name: 'String'
            }
          },
          attributes: {
            required: false,
            serializedName: 'attributes',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'AttributeElementType',
                  type: {
                    name: 'Composite',
                    className: 'Attribute'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = Device;
