/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Device group.
 *
 */
class Group {
  /**
   * Create a Group.
   * @member {string} group
   */
  constructor() {
  }

  /**
   * Defines the metadata of Group
   *
   * @returns {object} metadata of Group
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Group',
      type: {
        name: 'Composite',
        className: 'Group',
        modelProperties: {
          group: {
            required: true,
            serializedName: 'group',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = Group;
