/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as moment from "moment";


/**
 * @class
 * Initializes a new instance of the Attribute class.
 * @constructor
 * Attribute descriptor.
 *
 * @member {string} name A human readable, unique attribute ID, e.g.
 * 'device_type', 'ip_addr', 'cpu_load', etc.
 * @member {string} [description] Attribute description.
 * @member {string} value The current value of the attribute.
 *
 * Attribute type is implicit, inferred from the JSON type.
 *
 * Supported types: number, string, array of numbers, array of strings. Mixed
 * arrays are not allowed.
 */
export interface Attribute {
  name: string;
  description?: string;
  value: string;
}

/**
 * @class
 * Initializes a new instance of the Device class.
 * @constructor
 * @member {string} [id] Mender-assigned unique ID.
 * @member {string} [updatedTs] Timestamp of the most recent attribute update.
 * @member {array} [attributes] A list of attribute descriptors.
 */
export interface Device {
  id?: string;
  updatedTs?: string;
  attributes?: Attribute[];
}

/**
 * @class
 * Initializes a new instance of the Group class.
 * @constructor
 * Device group.
 *
 * @member {string} group
 */
export interface Group {
  group: string;
}

/**
 * @class
 * Initializes a new instance of the ErrorModel class.
 * @constructor
 * Error descriptor.
 *
 * @member {string} [error] Description of the error.
 * @member {string} [requestId] Request ID (same as in X-MEN-RequestID header).
 */
export interface ErrorModel {
  error?: string;
  requestId?: string;
}
